# Generated by Django 5.0 on 2023-12-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pictures/default_picture.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
