# Generated by Django 5.0 on 2024-03-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Buyer'), (2, 'Tour_Agency'), (3, 'Hotel')], null=True),
        ),
    ]
