# Generated by Django 5.0 on 2024-01-31 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
