# Generated by Django 5.0 on 2024-02-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_packages_desc_package_package_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_activities',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='package_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='package_locations',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='package_pic',
            field=models.ImageField(blank=True, null=True, upload_to='package_pictures/'),
        ),
        migrations.AddField(
            model_name='package',
            name='package_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='package_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
