# Generated by Django 5.0 on 2024-03-28 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_userprofile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_author',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='package',
        ),
        migrations.RemoveField(
            model_name='package',
            name='package_author',
        ),
        migrations.RemoveField(
            model_name='packageimage',
            name='package',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='PackageImage',
        ),
    ]
