# Generated by Django 5.0 on 2024-03-30 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_feedback_feedback_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
    ]
