# Generated by Django 5.0 on 2024-03-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packages', '0003_booking_booked_by_feedback_feedback_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='rating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
