# Generated by Django 5.0 on 2024-04-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packages', '0008_booking_paid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='package_end_date',
        ),
        migrations.RemoveField(
            model_name='package',
            name='package_start_date',
        ),
        migrations.AddField(
            model_name='package',
            name='package_duration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
