# Generated by Django 5.0 on 2024-04-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packages', '0009_remove_package_package_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_duration',
            field=models.CharField(blank=True, null=True),
        ),
    ]
