# Generated by Django 5.0 on 2024-04-12 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Packages', '0010_alter_package_package_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='package_pic',
        ),
    ]
