# Generated by Django 5.0 on 2024-04-15 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Packages', '0011_remove_package_package_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
    ]
