# Generated by Django 5.0 on 2024-04-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packages', '0012_remove_feedback_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('1', 'Initiated'), ('2', 'Completed'), ('3', 'Failed')], default='1', max_length=15),
        ),
    ]
