# Generated by Django 5.0 on 2024-04-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packages', '0014_package_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_activities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_locations',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_title',
            field=models.CharField(max_length=255),
        ),
    ]
